name: 'Create README.md file'

on:
  push:
    branches:
      - fix/github-action-faqilure
  workflow_dispatch:

jobs:
  readme-create:
    name: 'readme-create' 
    runs-on: ubuntu-latest 

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB }}  

      - name: 'Generate README with terraform-docs'
        uses: terraform-docs/gh-actions@v1.3.0   
        with:
          working-dir: .
          output-file: README.md
          output-method: inject 
          git-push: "true"               
      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}
        if: always()